### ISSUE TITLE
Table: Listing of individual concentrations for each subject at each time

### ISSUE THREAD

**Issue by billdenney** [billdenney/pknca.reporting#2]
Move issue from billdenney/pknca#29

**Comment by john-harrold** [comment]
I've seen two different ways of representing this. One is to have a column for time, then columns for each individual (I'll call this method 1). Another is to have a subject ID column then a column for each time (I'll call this method 2). So I think it would be good to be able to pivot this table either way. Flextable will spill across pages so if a table has too many rows it's not a big deal. If it has too many columns it could become an issue. So it might be good to have a col_max argument where it will take your data frame of information and spilt it at col_max columns. 

For method 1 above we'd want to maintain the time column on each of the vertical splits. For method 2 we'd want to maintain the subject IDs.

**Comment by billdenney** [comment]
@john-harrold, can you please take a look at the PR I just made? (#9)  It has a brief vignette that describes how to do this.  It will make the wide data.frame and summarize it for you.  It won't do the long version or split on a given number of columns, yet.
