### ISSUE TITLE
Table: Summary statistics of each nominal time

### ISSUE THREAD

**Issue by billdenney** [billdenney/pknca.reporting#3]
Move issue from billdenney/pknca#30

**Comment by john-harrold** [comment]
Would this be stratified by group? I'd like to do something similar in terms of orientation mentioned here: 

https://github.com/billdenney/pknca.reporting/issues/2

I think it would be good to be able to specify mean or median and also standard deviation, standard error, or CV%.

**Comment by billdenney** [comment]
The new PR (mentioned in #2) does this including stratification by group.
